# These are supported funding model platforms

github: mithudso
patreon: mithudso
venmo: @Mitchphudson
paypal: https://www.paypal.com/ncp/payment/8WLQPBK6PHFX2
cashapp: 
buy_me_a_coffee: https://buymeacoffee.com/mitchphudsi

